root = "."
tmp_dir = "tmp"

[build]
  args_bin = []
  bin = "./tmp/main"
  cmd = "make minify-tailwind && make inject-tw && make gen-manifest && make notify-templ-proxy && go build -o ./tmp/main ."
  delay = 0
  exclude_dir = ["assets", "tmp", "gen", "static", "node_modules"]
  exclude_file = ["server/generated/tailwind.templ", "server/generated/tailwind_templ.go", "server/generated/generated-manifest.go"]
  exclude_regex = [".*\\.txt$"]
  exclude_unchanged = false
  follow_symlink = false
  full_bin = ""
  include_dir = []
  include_ext = ["go", "templ", "vue", "ts", "json", "css"]
  include_file = []
  kill_delay = "0s"
  log = "build-errors.log"
  poll = false
  poll_interval = 0
  post_cmd = []
  pre_cmd = []
  rerun = false
  rerun_delay = 500
  send_interrupt = false
  stop_on_error = false

[color]
  app = ""
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

[log]
  main_only = false
  silent = false
  time = false

[misc]
  clean_on_exit = false

# [proxy]
#   app_port = 0
#   enabled = false
#   proxy_port = 0

[screen]
  clear_on_rebuild = false
  keep_scroll = true
